version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
      - terraform plan --auto-approve
  
  build:
    commands:
      - terraform apply --auto-approve