version: 0.2
phases:
  pre_build:
    commands:
      - # Install Terraform
      - wget https://releases.hashicorp.com/terraform/1.7.4/terraform_1.2.0_linux_amd64.zip
      - unzip terraform_1.7.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  
  build:
    commands:
      - terraform init
      - terraform validate
      - terraform plan
      - terraform apply --auto-approve