version: 0.2
phases:
  pre_build:
    commands:
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install -y terraform
  
  build:
    commands:
      -  /opt/terraform/terraform init
      - terraform validate
      - terraform apply --auto-approve