version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install Terraform
      - wget -O - https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install terraform

  pre_build:
    commands:
      # (Optional) Pre-build commands if needed

  build:
    commands:
      # Initialize Terraform
      - terraform init

      # Apply Terraform configuration
      - terraform apply -auto-approve

